__author__ = 'rodrigo'

file = open("dataset/cuephrases.txt")
document = file.readlines()

cue_phrases = []
for item in document:
    if item not in cue_phrases:
        cue_phrases.append(item)


# cue_phrases = [
#     'incidentally',
#     'for example',
#     'anyway',
#     'by the way',
#     'furthermore',
#     'first',
#     'second',
#     'moreover',
#     'therefore',
#     'and on the other hand',
#     'in summary',
#     'in conclusion',
#     'our investigation',
#     'the paper describes',
#     'the most important',
#     'according to the study',
#     'significantly',
#     'in particular',
#     'hardly',
#     'impossible',
#     'The purpose',
#     'The information'
# ]
#
# conj_adverb = [
#     'above all',
#     'accordingly',
#     'actually',
#     'admittedly',
#     'after all',
#     'after that',
#     'afterwards',
#     'again',
#     'all in all',
#     'all the same',
#     'also',
#     'alternatively',
#     'another time',
#     'anyway',
#     'as a consequence',
#     'as a corollary',
#     'as a result',
#     'as it happened',
#     'as it is',
#     'as it turned out',
#     'as luck would have it',
#     'as well',
#     'at any rate',
#     'at first',
#     'at first blush',
#     'at first sight',
#     'at first view',
#     'at least',
#     'at once',
#     'at that',
#     'at the outset',
#     'at the same time',
#     'before',
#     'before long',
#     'besides',
#     'by all means',
#     'by and by',
#     'by comparison',
#     'by contrast',
#     'by the same token',
#     'by the way',
#     'certainly',
#     'clearly',
#     'come to think of it',
#     'consequently',
#     'conversely',
#     'correspondingly',
#     'despite this',
#     'earlier',
#     'either',
#     'equally',
#     'essentially, then',
#     'even',
#     'even so',
#     'even then',
#     'eventually',
#     'ever since',
#     'except',
#     'failing that',
#     'finally',
#     'first',
#     'first of all',
#     'firstly',
#     'following this',
#     'for a start',
#     'for another thing',
#     'for example',
#     'for instance',
#     'for one thing',
#     'for that matter',
#     'for this reason',
#     'fortunately',
#     'further',
#     'furthermore',
#     'having said that',
#     'hence',
#     'however',
#     'if not',
#     'if so',
#     'in a different vein',
#     'in actual fact',
#     'in addition',
#     'in any case',
#     'in conclusion',
#     'in contrast',
#     'in fact',
#     'in other words',
#     'in particular',
#     'in short',
#     'in spite that',
#     'in sum',
#     'in that case',
#     'in the beginning',
#     'in the case of',
#     'in the end',
#     'in the event',
#     'in the first place',
#     'in the hope that',
#     'in the meantime',
#     'in this way',
#     'in truth',
#     'in turn',
#     'in which case',
#     'incidentally',
#     'indeed',
#     'initially',
#     'instantly',
#     'instead',
#     'just',
#     'just then',
#     'last',
#     'lastly',
#     'later',
#     'likewise',
#     'luckily',
#     'mainly because',
#     'meanwhile',
#     'merely',
#     'mind you',
#     'moreover',
#     'much later',
#     'much sooner',
#     'naturally',
#     'nevertheless',
#     'next',
#     'no doubt',
#     'nonetheless',
#     'not because',
#     'not only',
#     'not that',
#     'notably',
#     'on the contrary',
#     'on the one hand',
#     'on the one side',
#     'on the other hand',
#     'on the other side',
#     'on top of this',
#     'once again',
#     'once more',
#     'originally',
#     'otherwise',
#     'overall',
#     'plainly',
#     'presently',
#     'previously',
#     'put another way',
#     'rather',
#     'reciprocally',
#     'regardless of that',
#     'second',
#     'secondly',
#     'similarly',
#     'simultaneously',
#     'soon',
#     'specifically',
#     'still',
#     'subsequently',
#     'suddenly',
#     'summarising',
#     'summing up',
#     'sure enough',
#     'surely',
#     'that is',
#     'that is to say',
#     'then again',
#     'thereafter',
#     'thereby',
#     'therefore',
#     'third',
#     'thirdly',
#     'this time',
#     'though',
#     'thus',
#     'to be sure',
#     'to begin with',
#     'to conclude',
#     'to make matters worse',
#     'to start with',
#     'to sum up',
#     'to summarise',
#     'to take an example',
#     'too',
#     'true',
#     'ultimately',
#     'undoubtedly',
#     'unfortunately',
#     'well',
#     'what is more',
#     'whereas',
#     'whereupon'
# ]